---
- name: run modify_bootstrap_ign.py
  local_action: shell cd "{{ openshift_upi_directory }}" && python modify_bootstrap_ign.py

- name: run disable_afterburn_service.py
  local_action: shell cd "{{ openshift_upi_directory }}" && python disable_afterburn_service.py

- name: run update_master_ignition.sh
  local_action: shell cd "{{ openshift_upi_directory }}" && /bin/bash update_master_ignition.sh

- name: run modify_master_ign.py
  local_action: shell cd "{{ openshift_upi_directory }}" && python modify_master_ign.py
